import '@testing-library/jest-dom/vitest';
import { cleanup } from '@testing-library/react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { afterEach } from 'vitest';
import type { DashboardSettings, ElectronApi } from '../shared/types';
import en from '../i18n/en.json';
import { fakeEmail } from './fakeData';

if (!i18n.isInitialized) {
  void i18n.use(initReactI18next).init({
    resources: { en: { translation: en } },
    lng: 'en',
    fallbackLng: 'en',
    interpolation: { escapeValue: false, prefix: '{', suffix: '}' },
  });
}

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }),
});

const defaultSettings: DashboardSettings = {
  theme: 'auto',
  stickyThreadsEnabled: false,
  upstreamStreamTransport: 'default',
  preferEarlierResetAccounts: false,
  routingStrategy: 'weighted_round_robin',
  strictLockPoolContinuations: false,
  lockedRoutingAccountIds: [],
  openaiCacheAffinityMaxAgeSeconds: 300,
  importWithoutOverwrite: false,
  totpRequiredOnLogin: false,
  totpConfigured: false,
  apiKeyAuthEnabled: false,
  routingHeadroomWeightPrimary: 0.35,
  routingHeadroomWeightSecondary: 0.65,
  routingScoreAlpha: 0.3,
  routingScoreBeta: 0.25,
  routingScoreGamma: 0.2,
  routingScoreDelta: 0.2,
  routingScoreZeta: 0.05,
  routingScoreEta: 1,
  routingSuccessRateRho: 2,
  routingPlanModelPricingUsdPerMillion: '',
  syncClusterName: 'default',
  syncSiteId: 1,
  syncPort: 9400,
  syncDiscoveryEnabled: true,
  syncIntervalSeconds: 5,
  syncConflictResolution: 'lww',
  syncJournalRetentionDays: 30,
  syncTlsEnabled: true,
  syncRequireHandshakeAuth: true,
  syncClusterSharedSecret: '',
  syncTlsVerifyPeer: true,
  syncTlsCaCertificatePath: '',
  syncTlsCertificateChainPath: '',
  syncTlsPrivateKeyPath: '',
  syncTlsPinnedPeerCertificateSha256: '',
  syncSchemaVersion: 1,
  syncMinSupportedSchemaVersion: 1,
  syncAllowSchemaDowngrade: false,
  syncPeerProbeEnabled: true,
  syncPeerProbeIntervalMs: 5000,
  syncPeerProbeTimeoutMs: 500,
  syncPeerProbeMaxPerRefresh: 2,
  syncPeerProbeFailClosed: true,
  syncPeerProbeFailClosedFailures: 3,
};

Object.defineProperty(window, 'tightrope', {
  writable: true,
  value: {
    platform: 'darwin',
    getAppMeta: async () => ({ version: '0.1.0', buildChannel: 'dev', packaged: false }),
    getHealth: async () => ({ status: 'ok', uptime_ms: 1 }),
    getSettings: async () => ({ ...defaultSettings }),
    updateSettings: async (update) => ({ ...defaultSettings, ...(update ?? {}) }),
    changeDatabasePassphrase: async () => ({ status: 'ok' }),
    exportDatabase: async () => ({ success: true }),
    oauthStart: async () => ({
      method: 'browser',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
      callbackUrl: 'http://localhost:1455/auth/callback',
      verificationUrl: null,
      userCode: null,
      deviceAuthId: null,
      intervalSeconds: null,
      expiresInSeconds: null,
    }),
    oauthStatus: async () => ({
      status: 'pending',
      errorMessage: null,
      listenerRunning: false,
      callbackUrl: 'http://localhost:1455/auth/callback',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
    }),
    oauthStop: async () => ({
      status: 'stopped',
      errorMessage: null,
      listenerRunning: false,
      callbackUrl: 'http://localhost:1455/auth/callback',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
    }),
    oauthRestart: async () => ({
      method: 'browser',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=restart',
      callbackUrl: 'http://localhost:1455/auth/callback',
      verificationUrl: null,
      userCode: null,
      deviceAuthId: null,
      intervalSeconds: null,
      expiresInSeconds: null,
    }),
    oauthComplete: async () => ({ status: 'pending' }),
    oauthManualCallback: async () => ({ status: 'success', errorMessage: null }),
    onOauthDeepLink: () => () => {},
    onAboutOpen: () => () => {},
    listAccounts: async () => ({ accounts: [] }),
    listStickySessions: async () => ({ generatedAtMs: Date.now(), sessions: [] }),
    purgeStaleSessions: async () => ({ generatedAtMs: Date.now(), purged: 0 }),
    listRequestLogs: async () => ({ limit: 200, offset: 0, logs: [] }),
    listAccountTraffic: async () => ({ generatedAtMs: Date.now(), accounts: [] }),
    importAccount: async ({ email, provider }: { email: string; provider: string }) => ({
      accountId: '1',
      email,
      provider,
      status: 'active',
    }),
    previewSqlImport: async () => ({
      source: {
        path: '/tmp/sample.db',
        fileName: 'sample.db',
        sizeBytes: 0,
        modifiedAtMs: 0,
        schemaFingerprint: 'accounts:',
      },
      totals: {
        scanned: 0,
        newCount: 0,
        updateCount: 0,
        skipCount: 0,
        invalidCount: 0,
      },
      rows: [],
      warnings: [],
    }),
    applySqlImport: async () => ({
      totals: {
        scanned: 0,
        inserted: 0,
        updated: 0,
        skipped: 0,
        invalid: 0,
        failed: 0,
      },
      warnings: [],
    }),
    pinAccount: async () => ({ status: 'pinned' }),
    unpinAccount: async () => ({ status: 'unpinned' }),
    pauseAccount: async () => ({ status: 'paused' }),
    reactivateAccount: async () => ({ status: 'reactivated' }),
    deleteAccount: async () => ({ status: 'deleted' }),
    refreshAccountUsageTelemetry: async (accountId: string) => ({
      accountId,
      email: fakeEmail(`usage-${accountId}`),
      provider: 'openai',
      status: 'active',
    }),
    refreshAccountToken: async (accountId: string) => ({
      accountId,
      email: fakeEmail(`token-${accountId}`),
      provider: 'openai',
      status: 'active',
    }),
    listFirewallIps: async () => ({ mode: 'allow_all', entries: [] }),
    addFirewallIp: async (ipAddress: string) => ({ ipAddress, createdAt: 'now' }),
    removeFirewallIp: async () => ({ status: 'deleted' }),
    getBackendStatus: async () => ({ enabled: true }),
    startBackend: async () => ({ enabled: true }),
    stopBackend: async () => ({ enabled: false }),
    clusterEnable: async () => {},
    clusterDisable: async () => {},
    getClusterStatus: async () => ({
      enabled: false,
      site_id: '',
      cluster_name: '',
      role: 'standalone',
      term: 0,
      commit_index: 0,
      leader_id: null,
      peers: [],
      replication_lagging_peers: 0,
      replication_lag_total_entries: 0,
      replication_lag_max_entries: 0,
      replication_lag_avg_entries: 0,
      replication_lag_ewma_entries: 0,
      replication_lag_ewma_samples: 0,
      replication_lag_alert_threshold_entries: 0,
      replication_lag_alert_sustained_refreshes: 0,
      replication_lag_alert_streak: 0,
      replication_lag_alert_active: false,
      replication_lag_last_alert_at: null,
      ingress_socket_accept_failures: 0,
      ingress_socket_accepted_connections: 0,
      ingress_socket_completed_connections: 0,
      ingress_socket_failed_connections: 0,
      ingress_socket_active_connections: 0,
      ingress_socket_peak_active_connections: 0,
      ingress_socket_tls_handshake_failures: 0,
      ingress_socket_read_failures: 0,
      ingress_socket_apply_failures: 0,
      ingress_socket_handshake_ack_failures: 0,
      ingress_socket_bytes_read: 0,
      ingress_socket_total_connection_duration_ms: 0,
      ingress_socket_last_connection_duration_ms: 0,
      ingress_socket_max_connection_duration_ms: 0,
      ingress_socket_connection_duration_ewma_ms: 0,
      ingress_socket_connection_duration_le_10ms: 0,
      ingress_socket_connection_duration_le_50ms: 0,
      ingress_socket_connection_duration_le_250ms: 0,
      ingress_socket_connection_duration_le_1000ms: 0,
      ingress_socket_connection_duration_gt_1000ms: 0,
      ingress_socket_max_buffered_bytes: 0,
      ingress_socket_max_queued_frames: 0,
      ingress_socket_max_queued_payload_bytes: 0,
      ingress_socket_paused_read_cycles: 0,
      ingress_socket_paused_read_sleep_ms: 0,
      ingress_socket_last_connection_at: null,
      ingress_socket_last_failure_at: null,
      ingress_socket_last_failure_error: null,
      journal_entries: 0,
      pending_raft_entries: 0,
      last_sync_at: null,
    }),
    addPeer: async () => {},
    removePeer: async () => {},
    triggerSync: async () => {},
    rollbackSyncBatch: async () => {},
    onSyncEvent: () => () => {},
    windowMinimize: async () => {},
    windowToggleMaximize: async () => {},
    windowClose: async () => {},
    windowIsMaximized: async () => false,
  } satisfies ElectronApi,
});

afterEach(() => {
  cleanup();
});
