import '@testing-library/jest-dom/vitest';
import { cleanup } from '@testing-library/react';
import { afterEach } from 'vitest';
import type { DashboardSettings, ElectronApi } from '../shared/types';

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }),
});

const defaultSettings: DashboardSettings = {
  theme: 'auto',
  stickyThreadsEnabled: false,
  upstreamStreamTransport: 'default',
  preferEarlierResetAccounts: false,
  routingStrategy: 'usage_weighted',
  openaiCacheAffinityMaxAgeSeconds: 300,
  importWithoutOverwrite: false,
  totpRequiredOnLogin: false,
  totpConfigured: false,
  apiKeyAuthEnabled: false,
  routingHeadroomWeightPrimary: 0.35,
  routingHeadroomWeightSecondary: 0.65,
  routingScoreAlpha: 0.3,
  routingScoreBeta: 0.25,
  routingScoreGamma: 0.2,
  routingScoreDelta: 0.2,
  routingScoreZeta: 0.05,
  routingScoreEta: 1,
  routingSuccessRateRho: 2,
  syncClusterName: 'default',
  syncSiteId: 1,
  syncPort: 9400,
  syncDiscoveryEnabled: true,
  syncIntervalSeconds: 5,
  syncConflictResolution: 'lww',
  syncJournalRetentionDays: 30,
  syncTlsEnabled: true,
};

Object.defineProperty(window, 'tightrope', {
  writable: true,
  value: {
    platform: 'darwin',
    getHealth: async () => ({ status: 'ok', uptime_ms: 1 }),
    getSettings: async () => ({ ...defaultSettings }),
    updateSettings: async (update) => ({ ...defaultSettings, ...(update ?? {}) }),
    oauthStart: async () => ({
      method: 'browser',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
      callbackUrl: 'http://localhost:1455/auth/callback',
      verificationUrl: null,
      userCode: null,
      deviceAuthId: null,
      intervalSeconds: null,
      expiresInSeconds: null,
    }),
    oauthStatus: async () => ({
      status: 'pending',
      errorMessage: null,
      listenerRunning: false,
      callbackUrl: 'http://localhost:1455/auth/callback',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
    }),
    oauthStop: async () => ({
      status: 'stopped',
      errorMessage: null,
      listenerRunning: false,
      callbackUrl: 'http://localhost:1455/auth/callback',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=test',
    }),
    oauthRestart: async () => ({
      method: 'browser',
      authorizationUrl: 'https://auth.openai.com/oauth/authorize?response_type=code&state=restart',
      callbackUrl: 'http://localhost:1455/auth/callback',
      verificationUrl: null,
      userCode: null,
      deviceAuthId: null,
      intervalSeconds: null,
      expiresInSeconds: null,
    }),
    oauthComplete: async () => ({ status: 'pending' }),
    oauthManualCallback: async () => ({ status: 'success', errorMessage: null }),
    onOauthDeepLink: () => () => {},
    listAccounts: async () => ({ accounts: [] }),
    listRequestLogs: async () => ({ limit: 200, offset: 0, logs: [] }),
    listAccountTraffic: async () => ({ generatedAtMs: Date.now(), accounts: [] }),
    importAccount: async ({ email, provider }: { email: string; provider: string }) => ({
      accountId: '1',
      email,
      provider,
      status: 'active',
    }),
    pauseAccount: async () => ({ status: 'paused' }),
    reactivateAccount: async () => ({ status: 'reactivated' }),
    deleteAccount: async () => ({ status: 'deleted' }),
    refreshAccountUsageTelemetry: async (accountId: string) => ({
      accountId,
      email: `${accountId}@example.com`,
      provider: 'openai',
      status: 'active',
    }),
    listFirewallIps: async () => ({ mode: 'allow_all', entries: [] }),
    addFirewallIp: async (ipAddress: string) => ({ ipAddress, createdAt: 'now' }),
    removeFirewallIp: async () => ({ status: 'deleted' }),
    clusterEnable: async () => {},
    clusterDisable: async () => {},
    getClusterStatus: async () => ({
      enabled: false,
      site_id: '',
      cluster_name: '',
      role: 'standalone',
      term: 0,
      commit_index: 0,
      leader_id: null,
      peers: [],
      journal_entries: 0,
      pending_raft_entries: 0,
      last_sync_at: null,
    }),
    addPeer: async () => {},
    removePeer: async () => {},
    triggerSync: async () => {},
    rollbackSyncBatch: async () => {},
    windowMinimize: async () => {},
    windowToggleMaximize: async () => {},
    windowClose: async () => {},
    windowIsMaximized: async () => false,
  } satisfies ElectronApi,
});

afterEach(() => {
  cleanup();
});
